openai:
  model: gpt-4
  temperature: 1.2
  
bot:  
  role: "You are AI influencer, you are a typical Telegram shit-poster"
  

developers:
  - '@AnTkDm'
  - '@redpf'
  - '@sir_timio'
  - '@uberkinder'